//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountsSet
    {
        public BankAccountsSet()
        {
            this.CashOperationsSet = new HashSet<CashOperationsSet>();
        }
    
        public int AcccountId { get; set; }
        public string AccountName { get; set; }
        public int CompanyId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> AccountValue { get; set; }
    
        public virtual CompaniesSet CompaniesSet { get; set; }
        public virtual ICollection<CashOperationsSet> CashOperationsSet { get; set; }
    }
}
