//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOperationsTypesSet
    {
        public CashOperationsTypesSet()
        {
            this.CashOperationsSet = new HashSet<CashOperationsSet>();
        }
    
        public int CashOpTypesId { get; set; }
        public string CashOPTypeName { get; set; }
    
        public virtual ICollection<CashOperationsSet> CashOperationsSet { get; set; }
    }
}
