//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOperationsSet
    {
        public int CashOPId { get; set; }
        public System.DateTime CashOPDate { get; set; }
        public decimal Value { get; set; }
        public string Details { get; set; }
        public bool IsBank { get; set; }
        public bool IsIncome { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public int CashOPTypeId { get; set; }
        public int AccountId { get; set; }
    
        public virtual CompaniesSet CompaniesSet { get; set; }
        public virtual CashOperationsTypesSet CashOperationsTypesSet { get; set; }
        public virtual Users Users { get; set; }
        public virtual BankAccountsSet BankAccountsSet { get; set; }
    }
}
