//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsServices
    {
        public int ClientsServicesId { get; set; }
        public int Clientid { get; set; }
        public int ServiceId { get; set; }
        public bool IsPayer { get; set; }
    
        public virtual ServicesSet ServicesSet { get; set; }
        public virtual ClientsSet ClientsSet { get; set; }
    }
}
