//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoinExchangesSet
    {
        public int ExchangeId { get; set; }
        public string IntUSDChange { get; set; }
        public string ExtEURChange { get; set; }
        public string AddedPercent { get; set; }
        public string AddedValue { get; set; }
    }
}
