//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCashOP
    {
        public int CashOPId { get; set; }
        public string CashOPDate { get; set; }
        public string Value { get; set; }
        public string Details { get; set; }
        public string CashValue { get; set; }
        public string BankValue { get; set; }
        public string debtsToPay { get; set; }
        public string DebtsToRecieve { get; set; }
        public string InventValue { get; set; }
    
        public virtual CompanyCashOP CompanyCashOP1 { get; set; }
        public virtual CompanyCashOP CompanyCashOP2 { get; set; }
    }
}
