//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContabilidadEntities : DbContext
    {
        public ContabilidadEntities()
            : base("name=ContabilidadEntities")
        {
        }
        public ContabilidadEntities(string conn)
            : base(conn)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirTicketsSet> AirTicketsSet { get; set; }
        public virtual DbSet<ClientsServices> ClientsServices { get; set; }
        public virtual DbSet<CoinExchangesSet> CoinExchangesSet { get; set; }
        public virtual DbSet<CompaniesSet> CompaniesSet { get; set; }
        public virtual DbSet<CountriesSet> CountriesSet { get; set; }
        public virtual DbSet<EalthServicesSet> EalthServicesSet { get; set; }
        public virtual DbSet<ExpensesSet> ExpensesSet { get; set; }
        public virtual DbSet<HotelsSet> HotelsSet { get; set; }
        public virtual DbSet<IncomesSet> IncomesSet { get; set; }
        public virtual DbSet<IncomeTableSet> IncomeTableSet { get; set; }
        public virtual DbSet<InventariosSet> InventariosSet { get; set; }
        public virtual DbSet<PartnersServices> PartnersServices { get; set; }
        public virtual DbSet<PartnersSet> PartnersSet { get; set; }
        public virtual DbSet<Permisions> Permisions { get; set; }
        public virtual DbSet<PermissionsTypes> PermissionsTypes { get; set; }
        public virtual DbSet<ProductosSet> ProductosSet { get; set; }
        public virtual DbSet<PropertiesSet> PropertiesSet { get; set; }
        public virtual DbSet<ServicesSet> ServicesSet { get; set; }
        public virtual DbSet<ServiceTypes> ServiceTypes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ToursSet> ToursSet { get; set; }
        public virtual DbSet<TrainTicketsSet> TrainTicketsSet { get; set; }
        public virtual DbSet<TransferSet> TransferSet { get; set; }
        public virtual DbSet<UserButtonsSet> UserButtonsSet { get; set; }
        public virtual DbSet<UserCompanies> UserCompanies { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<ClientsSet> ClientsSet { get; set; }
        public virtual DbSet<CashOperationsTypesSet> CashOperationsTypesSet { get; set; }
        public virtual DbSet<CashOperationsSet> CashOperationsSet { get; set; }
        public virtual DbSet<CompanyCashOP> CompanyCashOP { get; set; }
        public virtual DbSet<BankAccountsSet> BankAccountsSet { get; set; }
    }
}
