//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class EalthServicesSet
    {
        public int EalthServiceId { get; set; }
        public string EalthServiceName { get; set; }
        public string CreationDate { get; set; }
        public string Partner { get; set; }
        public string Netprice { get; set; }
        public string BrutPrice { get; set; }
        public string OfferPrice { get; set; }
        public string OfferpriceSpan { get; set; }
        public string BrutOfferSpan { get; set; }
        public string Number { get; set; }
        public int CompanyId { get; set; }
    
        public virtual CompaniesSet CompaniesSet { get; set; }
    }
}
