//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesSet
    {
        public int PartnerServicesID { get; set; }
        public int ExpenseId { get; set; }
        public System.DateTime FactDate { get; set; }
        public decimal Value { get; set; }
        public decimal CoinExange { get; set; }
        public bool BankPaid { get; set; }
        public string Details { get; set; }
    
        public virtual PartnersServices PartnersServices { get; set; }
        public virtual ServicesSet ServicesSet { get; set; }
    }
}
