//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelsSet
    {
        public int HotelId { get; set; }
        public string Hotelname { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ServicesPartnerId { get; set; }
        public Nullable<decimal> Netprice { get; set; }
        public Nullable<decimal> BrutPrice { get; set; }
        public Nullable<decimal> OfferPrice { get; set; }
        public Nullable<System.DateTime> OfferStartdate { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public int CountryId { get; set; }
        public string City { get; set; }
        public string Room { get; set; }
        public string Food { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckOutdate { get; set; }
        public Nullable<int> Nights { get; set; }
        public Nullable<int> HotelCat { get; set; }
        public string HotelCode { get; set; }
        public string HotelDetails { get; set; }
        public string Type { get; set; }
    
        public virtual CountriesSet CountriesSet { get; set; }
        public virtual PartnersServices PartnersServices { get; set; }
    }
}
