//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomesSet
    {
        public int IncomeId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime FactDate { get; set; }
        public decimal Value { get; set; }
        public decimal CoinExchange { get; set; }
        public bool IsBankPaid { get; set; }
        public string Details { get; set; }
    
        public virtual ServicesSet ServicesSet { get; set; }
    }
}
