//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeTableSet
    {
        public int IncomeTableId { get; set; }
        public string IncomeTableName { get; set; }
        public string User { get; set; }
        public string Service { get; set; }
        public string GraphType { get; set; }
        public string Expense { get; set; }
        public string Date { get; set; }
        public string DocType { get; set; }
        public string ExpectedIncome { get; set; }
        public string RealIncome { get; set; }
        public string Plannedincome { get; set; }
        public int CompaniesCompanyId { get; set; }
    
        public virtual CompaniesSet CompaniesSet { get; set; }
    }
}
