//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContabilidadEntities : DbContext
    {
        public ContabilidadEntities()
            : base("name=ContabilidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CoinExchangesSet> CoinExchangesSet { get; set; }
        public DbSet<CompaniesSet> CompaniesSet { get; set; }
        public DbSet<EalthServicesSet> EalthServicesSet { get; set; }
        public DbSet<FundsSet> FundsSet { get; set; }
        public DbSet<IncomeTableSet> IncomeTableSet { get; set; }
        public DbSet<InventariosSet> InventariosSet { get; set; }
        public DbSet<Permisions> Permisions { get; set; }
        public DbSet<PermissionsTypes> PermissionsTypes { get; set; }
        public DbSet<ProductosSet> ProductosSet { get; set; }
        public DbSet<PropertiesSet> PropertiesSet { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserButtonsSet> UserButtonsSet { get; set; }
        public DbSet<UserCompanies> UserCompanies { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserType> UserType { get; set; }
        public DbSet<ServiceTypes> ServiceTypes { get; set; }
        public DbSet<ClientsSet> ClientsSet { get; set; }
        public DbSet<ServicesSet> ServicesSet { get; set; }
        public DbSet<PartnersServices> PartnersServices { get; set; }
        public DbSet<PartnersSet> PartnersSet { get; set; }
        public DbSet<ClientsServices> ClientsServices { get; set; }
        public DbSet<CountriesSet> CountriesSet { get; set; }
        public DbSet<ExpensesTypesSet> ExpensesTypesSet { get; set; }
        public DbSet<IncomesSet> IncomesSet { get; set; }
        public DbSet<ExpensesSet> ExpensesSet { get; set; }
        public DbSet<ToursSet> ToursSet { get; set; }
        public DbSet<AirTicketsSet> AirTicketsSet { get; set; }
        public DbSet<TrainTicketsSet> TrainTicketsSet { get; set; }
        public DbSet<HotelsSet> HotelsSet { get; set; }
        public DbSet<TransferSet> TransferSet { get; set; }
    }
}
