//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersServices
    {
        public PartnersServices()
        {
            this.AirTicketsSet = new HashSet<AirTicketsSet>();
            this.ExpensesSet = new HashSet<ExpensesSet>();
            this.HotelsSet = new HashSet<HotelsSet>();
            this.ToursSet = new HashSet<ToursSet>();
            this.TrainTicketsSet = new HashSet<TrainTicketsSet>();
            this.TransferSet = new HashSet<TransferSet>();
        }
    
        public int PartnersServicesID { get; set; }
        public int PartnerId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual ICollection<AirTicketsSet> AirTicketsSet { get; set; }
        public virtual ICollection<ExpensesSet> ExpensesSet { get; set; }
        public virtual ICollection<HotelsSet> HotelsSet { get; set; }
        public virtual PartnersSet PartnersSet { get; set; }
        public virtual ServicesSet ServicesSet { get; set; }
        public virtual ICollection<ToursSet> ToursSet { get; set; }
        public virtual ICollection<TrainTicketsSet> TrainTicketsSet { get; set; }
        public virtual ICollection<TransferSet> TransferSet { get; set; }
    }
}
