//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionsTypes
    {
        public PermissionsTypes()
        {
            this.Permisions = new HashSet<Permisions>();
        }
    
        public int PermissionsTypesID { get; set; }
        public bool IsUserID { get; set; }
        public string PermissionTypeName { get; set; }
        public Nullable<int> PermisionValue { get; set; }
    
        public virtual ICollection<Permisions> Permisions { get; set; }
    }
}
