//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisions
    {
        public int UserPermissionsID { get; set; }
        public int UserID { get; set; }
        public int PermissionsTypeID { get; set; }
    
        public virtual PermissionsTypes PermissionsTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
