//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosSet
    {
        public int ProductoId { get; set; }
        public string ProductoName { get; set; }
        public string PriceinRub { get; set; }
        public string USDprice { get; set; }
        public string EURPrice { get; set; }
        public string EntryDate { get; set; }
        public string PriceSpan { get; set; }
        public string priceSpanOffer { get; set; }
        public string IsIndividual { get; set; }
        public string ProductTime { get; set; }
        public string Place { get; set; }
        public string Details { get; set; }
    }
}
