//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCompanies
    {
        public int UserCompanyID { get; set; }
        public int CompaniID { get; set; }
        public int UserID { get; set; }
        public bool Active { get; set; }
    
        public virtual CompaniesSet CompaniesSet { get; set; }
        public virtual Users Users { get; set; }
    }
}
