//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Permisions = new HashSet<Permisions>();
            this.ServicesSet = new HashSet<ServicesSet>();
            this.UserCompanies = new HashSet<UserCompanies>();
            this.CashOperationsSet = new HashSet<CashOperationsSet>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Notes { get; set; }
        public int UserTypeID { get; set; }
        public string Login { get; set; }
        public byte[] Password { get; set; }
        public string Email { get; set; }
        public bool ActiveUser { get; set; }
    
        public virtual ICollection<Permisions> Permisions { get; set; }
        public virtual ICollection<ServicesSet> ServicesSet { get; set; }
        public virtual ICollection<UserCompanies> UserCompanies { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<CashOperationsSet> CashOperationsSet { get; set; }
    }
}
